### ISSUE TITLE
Could you also run the laser for ms_hubert model in s3prl and share the superb benchmark results? 

### ISSUE THREAD

**Issue by raotnameh** [Trikaldarshi/LASER#1]
There is an active PR for MS-HuBERT paper model integration in s3prl[link](https://github.com/s3prl/s3prl/pull/555/files). 

The changes are not much. 

Simply add the below lines of code to s3prl/upstream/hubert/hubconf.py file. 
`def ms_hubert(refresh=False, **kwds):
    kwds[
        "ckpt"
    ] = "https://huggingface.co/s3prl/MS-HuBERT/resolve/main/iter3.pt" 
    return hubert_custom(refresh=refresh, **kwds)`

After this you can simply chose ms_hubert for -u argument. 

I tried to do it myself, but unable to get any good results. getting a PER of 15% for some reason, when I am already getting PER equals to 4.17 without using LASER. 

For your reference, the finetuning logs with laser looks like this: 
`wandb: - 0.000 MB of 0.000 MB uploaded
wandb: Run history:
wandb:  train_loss █▅▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: train_loss1 ▇██▆▅▄▄▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: train_loss2 █▄▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:  train_loss 14.25568
wandb: train_loss1 8.63272
wandb: train_loss2 14.0574
wandb: 
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /raid/home/hemantya/del/s3prl/s3prl/wandb/offline-run-20240905_004950-9umdqc6y
wandb: Find logs at: ./wandb/offline-run-20240905_004950-9umdqc6y/logs
wandb: WARNING The new W&B backend becomes opt-out in version 0.18.0; try it out with `wandb.require("core")`! See https://wandb.me/wandb-core for more information.
(s3prl) hemantya@dgx1:~/del/s3prl/s3prl$ 
`

Thanks.

**Comment by Trikaldarshi** [comment]
Hello,
Thanks for your interest in our work. This code can be adapted for MS-HuBERT (you need to modify the code in runner_part_freeze.py to to freeze/unfreeze layers for MS-HuBERT, as it was only written for base versions of HuBERT and WavLM). Since, MS-HuBERT was not an option, the code might have fine-tuned all the layers, and hence you got the degraded performance (i.e 15%), potentially due to representations collapse. You can try to keep all the layers frozen except the last two layers for MS-HuBERT( just add it in runner_part_freeze.py as one of the upstream model).
Let me know if you face any issues or need any help. Feel free to drop an email at: ameghanani1@sheffield.ac.uk for further discussion or comment here :)
